export const IP_URI = "https://api.ipify.org"
export const BASE_APP_URI = "https://profolyo.vercel.app"
export const BASE_APP_URI_LOCAL = "http://localhost:3000"
export const GITHUB_URI = "https://github.com/binaryshrey/Profolyo"
export const GITHUB_ISSUES_URI = "https://github.com/binaryshrey/Profolyo/issues"
export const LINKEDIN_URI = "https://in.linkedin.com/in/shreyanshsaurabh"
export const BETTERSTACK_URI = "https://profolyo.betteruptime.com/"